name: Build
on:
  push:
    branches: [test/riscv32]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  tests:
    runs-on: ubuntu-latest
      - ubuntu-latest
    steps:
      # Checkout repository and blst submodule.
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up GNU C compiler
        # if: matrix.arch == 'arm64'
        run: |
          curl -sL https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.11.22/riscv32-glibc-ubuntu-22.04-gcc-nightly-2024.11.22-nightly.tar.xz -o riscv32.tar.xz
          mkdir -p /opt/riscv32
          tar xf riscv32.tar.xz -C /opt/riscv32/
          #chmod -R +x /opt/riscv32/riscv
          #sudo chmod -R u+w /opt/riscv32/riscv/riscv32-unknown-linux-gnu
          #ls -l /opt/riscv32/riscv/riscv32-unknown-linux-gnu

      - name: Build
        run: |
          export PATH=/opt/riscv32/riscv/bin:$PATH
          #./build.sh CC=/opt/riscv32/riscv/bin/riscv32-unknown-linux-gnu-gcc -shared
          make -j8 CC=/opt/riscv32/riscv/bin/riscv32-unknown-linux-gnu-gcc

      # Run tests.
      - name: Test
        run: make test

      # Run sanitizers.
      # Doesn't work on Windows.
      - name: Clang Sanitizers
        run: make sanitize

      # Run static analyzer.
      # Doesn't work on Windows.
      - name: Clang Static Analyzer
        run: make analyze
