name: Build
on:
  push:
    branches: [test/riscv32]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository and blst submodule.
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up GNU C compiler
        run: |
          curl -sL https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.11.22/riscv32-glibc-ubuntu-22.04-llvm-nightly-2024.11.22-nightly.tar.xz -o riscv32.tar.xz
          mkdir -p /opt/riscv32
          tar xf riscv32.tar.xz -C /opt/riscv32/

      - name: Build
        run: |
          export PATH=/opt/riscv32/riscv/bin:$PATH
          make CC=/opt/riscv32/riscv/bin/riscv32-unknown-linux-gnu-clang

      # # Run tests.
      # - name: Test
      #   run: make test

      # # Run sanitizers.
      # # Doesn't work on Windows.
      # - name: Clang Sanitizers
      #   run: make sanitize

      # # Run static analyzer.
      # # Doesn't work on Windows.
      # - name: Clang Static Analyzer
      #   run: make analyze

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: .
          if-no-files-found: error
